language: node_js
node_js:
  - "0.11"
  - "0.10"
  - 4.1.1

before_script:
  - npm install
  - npm install -g grunt-cli

script:
  - gulp test

notifications:
  slack: chartjs:pcfCZR6ugg5TEcaLtmIfQYuA
